# Generated by Django 5.0.4 on 2024-04-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_category_job_description_job_excperience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
    ]
