# Generated by Django 5.0.4 on 2024-04-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website_url', models.URLField()),
                ('cv_file', models.FileField(upload_to='jobs/CVs/')),
                ('cover_letter', models.TextField()),
            ],
        ),
    ]
