# Generated by Django 5.0.4 on 2024-04-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='job.job'),
            preserve_default=False,
        ),
    ]
