# Generated by Django 5.0.4 on 2024-04-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_applyjob_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
