# Generated by Django 5.0.4 on 2024-04-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_applyjob_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='created_at',
        ),
    ]
