# Generated by Django 5.0.4 on 2024-04-28 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_remove_applyjob_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
