# Generated by Django 5.0.4 on 2024-04-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_applyjob_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
