# Generated by Django 5.0.4 on 2024-04-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_applyjob_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='created_at',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='applyed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
