# Generated by Django 5.0.4 on 2024-04-28 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_remove_applyjob_created_at_applyjob_applyed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='applyed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 14, 39, 15, 246752), null=True),
        ),
    ]
