# Generated by Django 5.0.4 on 2024-04-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_applyjob_applyed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='applyed_at',
        ),
    ]
