# Generated by Django 5.0.2 on 2024-05-01 08:12

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_job_benefits_job_qualifications_job_responsibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=job.models.helper_upload_image),
        ),
    ]
